### ISSUE TITLE
Bot joins and leaves

### ISSUE THREAD

**Issue by johna3212** [Sworder71/Rias#3]
While playing some music like 
.play sing me to sleep
1
bot joins and leave and gives error undefined

**Comment by johna3212** [comment]
`
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) [lavaplayer-1.3.10.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_221]
Caused by: java.lang.RuntimeException: Not success status code: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:86) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:115) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:104) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:149) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:165) ~[lavaplayer-1.3.10.jar!/:na]
        at java.io.DataInputStream.readByte(Unknown Source) ~[na:1.8.0_221]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:79) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:51) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:34) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67) ~[lavaplayer-1.3.10.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90) ~[lavaplayer-1.3.10.jar!/:na]
        ... 4 common frames omitted

2019-10-13 18:59:52.024  INFO 10348 --- [   XNIO-2 I/O-2] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"630076907613847574"}
2019-10-13 19:02:27.228  INFO 10348 --- [   XNIO-2 I/O-2] lavalink.server.io.SocketServer          : Connection closed from /127.0.0.1:64138 -- CloseStatus[code=1006, reason=]
2019-10-13 19:02:27.233  INFO 10348 --- [   XNIO-2 I/O-2] lavalink.server.io.SocketContext         : Shutting down 0 playing players.
2019-10-13 19:02:27.237  INFO 10348 --- [   XNIO-2 I/O-2] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring disabled.`
This is my lavalink jar output

**Comment by Sworder71** [comment]
Bonjour, l'erreur est vague, la musique marche t'elle quand même par moment ou pas du tout ? Par ailleurs, avez-vous la dernière version du serveur Lavalink ?

**Comment by johna3212** [comment]
yes i think i have latest version

**Comment by Sworder71** [comment]
Ok, in this line, you have the following error:
```Caused by: java.lang.RuntimeException: Not success status code: 403```

Does your bot has the join and speaking permission ?

**Comment by snowdqdzq** [comment]
J'ai le même problème et le bot a la permission de parler , une idée ?

**Comment by johna3212** [comment]
Yes, it works for me when I tried on vpn/docker.

**Comment by Sworder71** [comment]
I think that it's an issue with the Lavalink server, please report it here: [Frederikam/Lavalink](https://github.com/Frederikam/Lavalink)
